model: 'configs/models/babyGPTV.yaml'
optimizer: 'configs/optimizers/GPTV_optim.yaml'
dataset: 'configs/datasets/image_caption_set.yaml'

max_new_tokens: 1024
# condition_prompt: "\n"
temperature: 0.7
top_k: 50
seed: 321