model: 'configs/models/babyGPT_bias.yaml'
optimizer: 'configs/optimizers/default_optimizer.yaml'
dataset: 'configs/datasets/shakespeare_char_set.yaml'
trainer: 'configs/trainers/default_trainer.yaml'

max_new_tokens: 500
condition_prompt: "\n"
temperature: 0.8
top_k: 200
seed: 321