out_dir: 'output/shakespeare_char'
eval_interval: 250 # keep frequent because we'll overfit
log_interval: 10 # don't print too too often
epochs: 2
lr_decay_iters: 5000 # make equal to max_iters usually
min_lr: 1e-4 # learning_rate / 10 usually
warmup_iters: 100 # not super necessary potentially
batch_size: 256