eval_interval: 4000
eval_num_samples: 100
final_eval_samples: 10000

max_iters: 500000
# max_iters: 1
batch_size: 64
learning_rate: 1e-3 # with baby networks can afford to go a bit higher
beta1: 0.9
beta2: 0.999
# is 1e-2 better? no
weight_decay: 1e-1
decay_lr:
  warmup_iters: 500
  lr_decay_iters: 500000
  min_lr: 1e-5