out_dir: 'output/GPTV_pretrain'
eval_interval: 200
eval_num_samples: 10
final_eval_samples: 10000

max_iters: 10000
batch_size: 200
learning_rate: 1e-3 # with baby networks can afford to go a bit higher
beta1: 0.9
beta2: 0.999
weight_decay: 1e-1
decay_lr:
  warmup_iters: 50
  lr_decay_iters: 10000
  min_lr: 4e-5