out_dir: 'output/GPTV'
eval_interval: 50
eval_num_samples: 2
final_eval_samples: 200

max_iters: 1500
batch_size: 10
learning_rate: 3e-5
beta1: 0.9
beta2: 0.999
weight_decay: 5e-2
decay_lr:
  warmup_iters: 10
  lr_decay_iters: 1500
  min_lr: 2e-6